        name: My CI/CD Workflow

        on:
          push:
            branches:
              - main

        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
              - name: Check out code
                uses: actions/checkout@v3

              - name: Install dependencies
                run: |
                  pip install -r requirements.txt
                  echo "Dependencies installed"

              - name: Run tests
                run: |
                  python -m unittest discover -s tests
                  echo "Tests passed"

              - name: Build application
                run: |
                  python app.py
                  echo "Application built"